1: Hall.csv: none: {'count': 4310, 'truepos': 95, 'falseneg': 10, 'unknownyes': 1, 'falsepos': 408, 'unique': 4310}
1: Hall.csv: three: {'count': 1273, 'truepos': 102, 'falseneg': 0, 'unknownyes': 4, 'falsepos': 11, 'unique': 580}
1: Hall.csv: machine: {'count': 810, 'truepos': 95, 'falseneg': 6, 'unknownyes': 5, 'falsepos': 17, 'unique': 570}
1: Hall.csv: machine2: {'count': 772, 'truepos': 99, 'falseneg': 3, 'unknownyes': 4, 'falsepos': 16, 'unique': 520}
1: Hall.csv: machine3: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2a1-2>
Subject: Job 262447: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 1> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 1> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2a1-2>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Fri Oct 13 17:19:03 2017
Results reported at Fri Oct 13 20:50:41 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 1
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :  13806.91 sec.
    Max Memory :       194 MB
    Max Swap   :      1213 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/1.err.262447> for stderr output of this job.

