27: Hall.csv: none: {'count': 2760, 'truepos': 97, 'falseneg': 7, 'unknownyes': 2, 'falsepos': 247, 'unique': 2760}
27: Hall.csv: three: {'count': 4014, 'truepos': 100, 'falseneg': 4, 'unknownyes': 2, 'falsepos': 52, 'unique': 1840}
27: Hall.csv: machine: {'count': 520, 'truepos': 92, 'falseneg': 7, 'unknownyes': 7, 'falsepos': 6, 'unique': 360}
27: Hall.csv: machine2: {'count': 863, 'truepos': 98, 'falseneg': 4, 'unknownyes': 4, 'falsepos': 16, 'unique': 590}
27: Hall.csv: machine3: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2j1-5>
Subject: Job 262473: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 27> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 27> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2>.
Job was executed on host(s) <2*n2j1-5>, in queue <single_chassis>, as user <zyu9> in cluster <henry2>.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Fri Oct 13 17:19:03 2017
Results reported at Fri Oct 13 18:59:58 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 27
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :   7062.58 sec.
    Max Memory :       178 MB
    Max Swap   :      1196 MB

    Max Processes  :         3
    Max Threads    :         8

The output (if any) is above this job summary.



PS:

Read file <./err/27.err.262473> for stderr output of this job.

