5: Hall.csv: none: {'count': 4890, 'truepos': 73, 'falseneg': 31, 'correction': 0, 'unknownyes': 0, 'falsepos': 15, 'unique': 4890}
5: Hall.csv: three: {'count': 2458, 'truepos': 73, 'falseneg': 29, 'correction': 45, 'unknownyes': 2, 'falsepos': 0, 'unique': 1200}
5: Hall.csv: machine: {'count': 1557, 'truepos': 91, 'falseneg': 11, 'correction': 24, 'unknownyes': 2, 'falsepos': 5, 'unique': 1110}
5: Hall.csv: knee: {'count': 679, 'truepos': 91, 'falseneg': 11, 'correction': 26, 'unknownyes': 2, 'falsepos': 1, 'unique': 470}
5: Wahono.csv: none: 
------------------------------------------------------------
Sender: LSF System <lsfadmin@n2e1-10>
Subject: Job 760331: </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 5> in cluster <henry2> Exited

Job </share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 5> was submitted from host <login01.hpc.ncsu.edu> by user <zyu9> in cluster <henry2> at Sun Feb 25 12:29:23 2018.
Job was executed on host(s) <2*n2e1-10>, in queue <single_chassis>, as user <zyu9> in cluster <henry2> at Sun Feb 25 12:29:29 2018.
</home/zyu9> was used as the home directory.
</home/zyu9/projects/MAR_HPC/Error/src> was used as the working directory.
Started at Sun Feb 25 12:29:29 2018.
Terminated at Sun Feb 25 13:55:03 2018.
Results reported at Sun Feb 25 13:55:03 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/share/tjmenzie/zyu9/miniconda2/bin/python2.7 runner.py error_hpcc 5
------------------------------------------------------------

TERM_OWNER: job killed by owner.
Exited with exit code 1.

Resource usage summary:

    CPU time :                                   6078.50 sec.
    Max Memory :                                 216.84 MB
    Average Memory :                             176.40 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   1262 MB
    Max Processes :                              3
    Max Threads :                                8
    Run time :                                   5145 sec.
    Turnaround time :                            5140 sec.

The output (if any) is above this job summary.



PS: The stderr output (if any) follows:

Traceback (most recent call last):
  File "runner.py", line 352, in <module>
    eval(cmd())
  File "<string>", line 1, in <module>
  File "runner.py", line 296, in error_hpcc
    result = BM25(file,queries[file],'est','random')
  File "runner.py", line 206, in BM25
    a,b,c,d =read.train(weighting=True,pne=True)
  File "/home/zyu9/projects/MAR_HPC/Error/src/mar.py", line 584, in train
    self.est_num, self.est = self.estimate_curve(clf, reuse=False, num_neg=len(sample)-len(left))
  File "/home/zyu9/projects/MAR_HPC/Error/src/mar.py", line 356, in estimate_curve
    prob1 = clf.decision_function(self.csr_mat)
  File "/share/tjmenzie/zyu9/miniconda2/lib/python2.7/site-packages/sklearn/svm/base.py", line 527, in decision_function
    dec = self._decision_function(X)
  File "/share/tjmenzie/zyu9/miniconda2/lib/python2.7/site-packages/sklearn/svm/base.py", line 388, in _decision_function
    dec_func = self._sparse_decision_function(X)
  File "/share/tjmenzie/zyu9/miniconda2/lib/python2.7/site-packages/sklearn/svm/base.py", line 434, in _sparse_decision_function
    self.probA_, self.probB_)
KeyboardInterrupt


PS:

Fail to open stderr file ./err/5.err.760331: No such file or directory.
The stderr output is included in this report.

